- name: Create test directory.
  ansible.builtin.file:
    state: directory
    path: ../{{ item }}
  loop:
  - test2

- name: Create fluentd.conf template for tests.
  ansible.builtin.template:
    src: '{{ item }}/fluentd.conf.j2'
    dest: ../{{ item }}/fluentd.conf
  loop:
  - test2

- name: Create test.sh template for tests.
  ansible.builtin.template:
    src: '{{ item }}/{{ item }}.sh'
    dest: ../{{ item }}/{{ item }}.sh
    mode: u+x
  loop:
  - test2

- name: Create test directory.
  ansible.builtin.file:
    state: directory
    path: ../{{ item }}
  loop:
  - test2/logs

- name: Create log files
  ansible.builtin.template:
    src: test2/{{ item }}
    dest: ../test2/logs/{{ item }}
  loop:
  - php_errors.log
  - php_errors2.log
  - php_errors3.log
